.TH "AddEntityEvent" 3 "Fri Jul 24 2015" "Fortress" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AddEntityEvent \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <event\&.h>\fP
.PP
Inherits \fBEvent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAddEntityEvent\fP ()"
.br
.ti -1c
.RI "\fBEventType\fP \fBgetType\fP () const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBEntity\fP * \fBentity\fP"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBEventType\fP \fBm_type\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "AddEntityEvent::AddEntityEvent ()\fC [inline]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBEventType\fP Event::getType () const\fC [inline]\fP, \fC [inherited]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBEntity\fP* AddEntityEvent::entity"

.SS "\fBEventType\fP Event::m_type\fC [protected]\fP, \fC [inherited]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fortress from the source code\&.
