.TH "color.h" 3 "Fri Jul 24 2015" "Fortress" \" -*- nroff -*-
.ad l
.nh
.SH NAME
color.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBColor\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBCOLOR\fP { \fBRED\fP, \fBGREEN\fP, \fBBLUE\fP, \fBWHITE\fP, \fBBLACK\fP, \fBGREY\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBCOLOR\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIRED \fP\fP
.TP
\fB\fIGREEN \fP\fP
.TP
\fB\fIBLUE \fP\fP
.TP
\fB\fIWHITE \fP\fP
.TP
\fB\fIBLACK \fP\fP
.TP
\fB\fIGREY \fP\fP
.SH "Author"
.PP 
Generated automatically by Doxygen for Fortress from the source code\&.
