.TH "Color" 3 "Fri Jul 24 2015" "Fortress" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Color \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <color\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBColor\fP ()"
.br
.ti -1c
.RI "\fBColor\fP (float red, float green, float blue)"
.br
.ti -1c
.RI "\fBColor\fP (\fBCOLOR\fP color)"
.br
.ti -1c
.RI "float \fBRed\fP ()"
.br
.ti -1c
.RI "float \fBGreen\fP ()"
.br
.ti -1c
.RI "float \fBBlue\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "float \fBm_red\fP"
.br
.ti -1c
.RI "float \fBm_green\fP"
.br
.ti -1c
.RI "float \fBm_blue\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Color::Color ()\fC [inline]\fP"

.SS "Color::Color (floatred, floatgreen, floatblue)"

.SS "Color::Color (\fBCOLOR\fPcolor)"

.SH "Member Function Documentation"
.PP 
.SS "float Color::Blue ()\fC [inline]\fP"

.SS "float Color::Green ()\fC [inline]\fP"

.SS "float Color::Red ()\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "float Color::m_blue\fC [private]\fP"

.SS "float Color::m_green\fC [private]\fP"

.SS "float Color::m_red\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fortress from the source code\&.
