.TH "ComponentManager< T >" 3 "Fri Jul 24 2015" "Fortress" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ComponentManager< T > \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <component_manager\&.h>\fP
.PP
Inherits \fBComponentManagerInterface< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBadd\fP (\fBEntity\fP *entity, T component)"
.br
.ti -1c
.RI "T * \fBget\fP (\fBEntity\fP *entity)"
.br
.ti -1c
.RI "void \fBremove\fP (\fBEntity\fP *entity)"
.br
.ti -1c
.RI "std::map< \fBEntity\fP *, T > & \fBgetAll\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::map< \fBEntity\fP *, T > \fBm_components\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "template<class T> void \fBComponentManager\fP< T >::add (\fBEntity\fP *entity, Tcomponent)\fC [virtual]\fP"

.PP
Implements \fBComponentManagerInterface< T >\fP\&.
.SS "template<class T > T * \fBComponentManager\fP< T >::get (\fBEntity\fP *entity)\fC [virtual]\fP"

.PP
Implements \fBComponentManagerInterface< T >\fP\&.
.SS "template<class T> std::map<\fBEntity\fP*, T>& \fBComponentManager\fP< T >::getAll ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBComponentManagerInterface< T >\fP\&.
.SS "template<class T > void \fBComponentManager\fP< T >::remove (\fBEntity\fP *entity)\fC [virtual]\fP"

.PP
Implements \fBComponentManagerInterface< T >\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "template<class T> std::map<\fBEntity\fP*, T> \fBComponentManager\fP< T >::m_components\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fortress from the source code\&.
