.TH "component_manager.h" 3 "Fri Jul 24 2015" "Fortress" \" -*- nroff -*-
.ad l
.nh
.SH NAME
component_manager.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'component_manager_interface\&.h'\fP
.br
\fC#include 'entity\&.h'\fP
.br
\fC#include <map>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBComponentManager< T >\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Fortress from the source code\&.
