.TH "component_manager.cpp" 3 "Fri Jul 24 2015" "Fortress" \" -*- nroff -*-
.ad l
.nh
.SH NAME
component_manager.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'component_manager\&.h'\fP
.br
\fC#include 'entity\&.h'\fP
.br
\fC#include <map>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Fortress from the source code\&.
