.TH "ConfigManager" 3 "Fri Jul 24 2015" "Fortress" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ConfigManager \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <config_manager\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBsetTag\fP (const std::string &tag, const \fBTagValue\fP &val)"
.br
.ti -1c
.RI "\fBTagValue\fP \fBgetTag\fP (const std::string &tag)"
.br
.ti -1c
.RI "void \fBreadFile\fP (const std::string &config)"
.br
.ti -1c
.RI "void \fBstringToTagValue\fP (const std::string &input, \fBTagValue\fP &output)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "std::map< std::string, \fBTagValue\fP > \fBm_tags\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "\fBTagValue\fP ConfigManager::getTag (const std::string &tag)"

.SS "void ConfigManager::readFile (const std::string &config)"

.SS "void ConfigManager::setTag (const std::string &tag, const \fBTagValue\fP &val)"

.SS "void ConfigManager::stringToTagValue (const std::string &input, \fBTagValue\fP &output)"

.SH "Member Data Documentation"
.PP 
.SS "std::map<std::string, \fBTagValue\fP> ConfigManager::m_tags\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fortress from the source code\&.
