.TH "config_manager.cpp" 3 "Fri Jul 24 2015" "Fortress" \" -*- nroff -*-
.ad l
.nh
.SH NAME
config_manager.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <config_manager\&.h>\fP
.br
\fC#include <fstream>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <sstream>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Fortress from the source code\&.
