.TH "entity.cpp" 3 "Fri Jul 24 2015" "Fortress" \" -*- nroff -*-
.ad l
.nh
.SH NAME
entity.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'entity\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "bool \fBoperator<\fP (const \fBEntity\fP &lhs, const \fBEntity\fP &rhs)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "bool operator< (const \fBEntity\fP &lhs, const \fBEntity\fP &rhs)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Fortress from the source code\&.
