.TH "Entity" 3 "Fri Jul 24 2015" "Fortress" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Entity \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <entity\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBaddTag\fP (\fBTag\fP tag)"
.br
.ti -1c
.RI "std::set< \fBTag\fP > \fBgetTags\fP ()"
.br
.ti -1c
.RI "bool \fBhasTag\fP (\fBTag\fP tag)"
.br
.ti -1c
.RI "void \fBsetId\fP (\fBEntityId\fP id)"
.br
.ti -1c
.RI "\fBEntityId\fP \fBgetId\fP () const "
.br
.ti -1c
.RI "void \fBsetName\fP (const std::string &name)"
.br
.ti -1c
.RI "const std::string & \fBgetName\fP () const "
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBEntityId\fP \fBm_id\fP"
.br
.ti -1c
.RI "std::string \fBm_name\fP"
.br
.ti -1c
.RI "std::set< \fBTag\fP > \fBm_tags\fP"
.br
.in -1c
.SS "Friends"

.in +1c
.ti -1c
.RI "class \fBEntityManager\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void Entity::addTag (\fBTag\fPtag)\fC [inline]\fP"

.SS "\fBEntityId\fP Entity::getId () const\fC [inline]\fP"

.SS "const std::string& Entity::getName () const\fC [inline]\fP"

.SS "std::set<\fBTag\fP> Entity::getTags ()\fC [inline]\fP"

.SS "bool Entity::hasTag (\fBTag\fPtag)"

.SS "void Entity::setId (\fBEntityId\fPid)\fC [inline]\fP"

.SS "void Entity::setName (const std::string &name)\fC [inline]\fP"

.SH "Friends And Related Function Documentation"
.PP 
.SS "friend class \fBEntityManager\fP\fC [friend]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBEntityId\fP Entity::m_id\fC [private]\fP"

.SS "std::string Entity::m_name\fC [private]\fP"

.SS "std::set<\fBTag\fP> Entity::m_tags\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fortress from the source code\&.
