.TH "EventManager" 3 "Fri Jul 24 2015" "Fortress" \" -*- nroff -*-
.ad l
.nh
.SH NAME
EventManager \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <event_manager\&.h>\fP
.PP
Inherits \fBEventManagerInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBinitialise\fP (\fBGameEngineInterface\fP *engine)"
.br
.ti -1c
.RI "void \fBregisterHandler\fP (\fBGameSystemInterface\fP *system)"
.br
.ti -1c
.RI "void \fBraiseEvent\fP (\fBEvent\fP *event)"
.br
.ti -1c
.RI "void \fBprocessEvents\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBGameEngineInterface\fP * \fBm_engine\fP"
.br
.ti -1c
.RI "\fBEventQueue\fP \fBm_events\fP"
.br
.ti -1c
.RI "\fBHandlers\fP \fBm_handlers\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void EventManager::initialise (\fBGameEngineInterface\fP *engine)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBEventManagerInterface\fP\&.
.SS "void EventManager::processEvents ()\fC [virtual]\fP"

.PP
Implements \fBEventManagerInterface\fP\&.
.SS "void EventManager::raiseEvent (\fBEvent\fP *event)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBEventManagerInterface\fP\&.
.SS "void EventManager::registerHandler (\fBGameSystemInterface\fP *system)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBEventManagerInterface\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBGameEngineInterface\fP* EventManager::m_engine\fC [private]\fP"

.SS "\fBEventQueue\fP EventManager::m_events\fC [private]\fP"

.SS "\fBHandlers\fP EventManager::m_handlers\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fortress from the source code\&.
