.TH "Event" 3 "Fri Jul 24 2015" "Fortress" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Event \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <event\&.h>\fP
.PP
Inherited by \fBAddEntityEvent\fP, \fBAttackEntityEvent\fP, \fBMoveEntityEvent\fP, and \fBRemoveEntityEvent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEvent\fP (\fBEventType\fP type)"
.br
.ti -1c
.RI "virtual \fB~Event\fP ()"
.br
.ti -1c
.RI "\fBEventType\fP \fBgetType\fP () const "
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBEventType\fP \fBm_type\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Event::Event (\fBEventType\fPtype)\fC [inline]\fP"

.SS "virtual Event::~Event ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "\fBEventType\fP Event::getType () const\fC [inline]\fP"

.SH "Member Data Documentation"
.PP 
.SS "\fBEventType\fP Event::m_type\fC [protected]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fortress from the source code\&.
