.TH "gameengine.cpp" 3 "Fri Jul 24 2015" "Fortress" \" -*- nroff -*-
.ad l
.nh
.SH NAME
gameengine.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'gameengine\&.h'\fP
.br
\fC#include <string>\fP
.br
\fC#include 'generator\&.h'\fP
.br
\fC#include 'event_manager\&.h'\fP
.br
\fC#include 'entity_manager\&.h'\fP
.br
\fC#include 'window_manager\&.h'\fP
.br
\fC#include 'movement_system\&.h'\fP
.br
\fC#include 'combat_system\&.h'\fP
.br
\fC#include 'sprite_system\&.h'\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fBkeyDown\fP (unsigned char key, int x, int y)"
.br
.ti -1c
.RI "static void \fBkeyUp\fP (unsigned char key, int x, int y)"
.br
.ti -1c
.RI "static void \fBdisplay\fP (void)"
.br
.ti -1c
.RI "static void \fBmouseClick\fP (int button, int state, int x, int y)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "\fBGameEngine\fP * \fBg_engine\fP = 0"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "static void display (void)\fC [static]\fP"

.SS "static void keyDown (unsigned charkey, intx, inty)\fC [static]\fP"

.SS "static void keyUp (unsigned charkey, intx, inty)\fC [static]\fP"

.SS "static void mouseClick (intbutton, intstate, intx, inty)\fC [static]\fP"

.SH "Variable Documentation"
.PP 
.SS "\fBGameEngine\fP* g_engine = 0"

.SH "Author"
.PP 
Generated automatically by Doxygen for Fortress from the source code\&.
