.TH "game_engine_interface.h" 3 "Fri Jul 24 2015" "Fortress" \" -*- nroff -*-
.ad l
.nh
.SH NAME
game_engine_interface.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <string>\fP
.br
\fC#include 'entity_manager_interface\&.h'\fP
.br
\fC#include 'graphics_interface\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGameEngineInterface\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Fortress from the source code\&.
