.TH "generator_interface.h" 3 "Fri Jul 24 2015" "Fortress" \" -*- nroff -*-
.ad l
.nh
.SH NAME
generator_interface.h \- 
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGeneratorInterface\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Fortress from the source code\&.
