.TH "generator.h" 3 "Fri Jul 24 2015" "Fortress" \" -*- nroff -*-
.ad l
.nh
.SH NAME
generator.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'generator_interface\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGenerator\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Fortress from the source code\&.
