.TH "Generator" 3 "Fri Jul 24 2015" "Fortress" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Generator \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <generator\&.h>\fP
.PP
Inherits \fBGeneratorInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBinitialise\fP (\fBGameEngineInterface\fP *a_engine)"
.br
.ti -1c
.RI "void \fBgenerate\fP ()"
.br
.ti -1c
.RI "unsigned int & \fBmapHeight\fP ()"
.br
.ti -1c
.RI "unsigned int & \fBmapWidth\fP ()"
.br
.ti -1c
.RI "unsigned int & \fBnumberOfRooms\fP ()"
.br
.in -1c
.SS "Private Member Functions"

.in +1c
.ti -1c
.RI "bool \fBgenerateRoom\fP (char *map)"
.br
.ti -1c
.RI "void \fBloadMap\fP (char *map)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBGameEngineInterface\fP * \fBm_engine\fP"
.br
.ti -1c
.RI "unsigned int \fBm_mapHeight\fP"
.br
.ti -1c
.RI "unsigned int \fBm_mapWidth\fP"
.br
.ti -1c
.RI "unsigned int \fBm_rooms\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void Generator::generate ()\fC [virtual]\fP"

.PP
Implements \fBGeneratorInterface\fP\&.
.SS "bool Generator::generateRoom (char *map)\fC [private]\fP"

.SS "void Generator::initialise (\fBGameEngineInterface\fP *a_engine)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBGeneratorInterface\fP\&.
.SS "void Generator::loadMap (char *map)\fC [private]\fP"

.SS "unsigned int& Generator::mapHeight ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBGeneratorInterface\fP\&.
.SS "unsigned int& Generator::mapWidth ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBGeneratorInterface\fP\&.
.SS "unsigned int& Generator::numberOfRooms ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBGeneratorInterface\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBGameEngineInterface\fP* Generator::m_engine\fC [private]\fP"

.SS "unsigned int Generator::m_mapHeight\fC [private]\fP"

.SS "unsigned int Generator::m_mapWidth\fC [private]\fP"

.SS "unsigned int Generator::m_rooms\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fortress from the source code\&.
