.TH "graphics.h" 3 "Fri Jul 24 2015" "Fortress" \" -*- nroff -*-
.ad l
.nh
.SH NAME
graphics.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'color\&.h'\fP
.br
\fC#include 'graphics_interface\&.h'\fP
.br
\fC#include 'config_manager\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGraphics\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBICON_TYPE\fP { \fBICON_BRICK\fP = 247, \fBICON_MAX\fP = 12*48 }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBstart_graphics\fP ()"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBICON_TYPE\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\fB\fIICON_BRICK \fP\fP
.TP
\fB\fIICON_MAX \fP\fP
.SH "Function Documentation"
.PP 
.SS "void start_graphics ()"

.SH "Author"
.PP 
Generated automatically by Doxygen for Fortress from the source code\&.
