.TH "graphics_interface.h" 3 "Fri Jul 24 2015" "Fortress" \" -*- nroff -*-
.ad l
.nh
.SH NAME
graphics_interface.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'color\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGraphicsInterface\fP"
.br
.in -1c
.SS "Typedefs"

.in +1c
.ti -1c
.RI "typedef void(* \fBKeyboardFuncPtr\fP )(unsigned char key, int x, int y)"
.br
.ti -1c
.RI "typedef void(* \fBDisplayFuncPtr\fP )(void)"
.br
.ti -1c
.RI "typedef void(* \fBMouseFuncPtr\fP )(int button, int state, int x, int y)"
.br
.in -1c
.SH "Typedef Documentation"
.PP 
.SS "typedef void(* DisplayFuncPtr)(void)"

.SS "typedef void(* KeyboardFuncPtr)(unsigned char key, int x, int y)"

.SS "typedef void(* MouseFuncPtr)(int button, int state, int x, int y)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Fortress from the source code\&.
