.TH "GraphicsInterface" 3 "Fri Jul 24 2015" "Fortress" \" -*- nroff -*-
.ad l
.nh
.SH NAME
GraphicsInterface \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <graphics_interface\&.h>\fP
.PP
Inherited by \fBGraphics\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual \fB~GraphicsInterface\fP ()"
.br
.ti -1c
.RI "virtual void \fBinitialise\fP (int argc, char **argv)=0"
.br
.ti -1c
.RI "virtual void \fBspin\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBbeginScreenUpdate\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBendScreenUpdate\fP ()=0"
.br
.ti -1c
.RI "virtual void \fBdrawString\fP (int y, int x, const char *s)=0"
.br
.ti -1c
.RI "virtual void \fBdrawTile\fP (int y, int x, unsigned int tile, \fBColor\fP fg, \fBColor\fP bg)=0"
.br
.ti -1c
.RI "virtual void \fBdrawBorder\fP (int y, int x, int height, int width)=0"
.br
.ti -1c
.RI "virtual void \fBsetKeyboardFunc\fP (\fBKeyboardFuncPtr\fP func)=0"
.br
.ti -1c
.RI "virtual void \fBsetKeyboardUpFunc\fP (\fBKeyboardFuncPtr\fP func)=0"
.br
.ti -1c
.RI "virtual void \fBsetDisplayFunc\fP (\fBDisplayFuncPtr\fP func)=0"
.br
.ti -1c
.RI "virtual void \fBsetMouseFunc\fP (\fBMouseFuncPtr\fP func)=0"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "virtual GraphicsInterface::~GraphicsInterface ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "virtual void GraphicsInterface::beginScreenUpdate ()\fC [pure virtual]\fP"

.PP
Implemented in \fBGraphics\fP\&.
.SS "virtual void GraphicsInterface::drawBorder (inty, intx, intheight, intwidth)\fC [pure virtual]\fP"

.PP
Implemented in \fBGraphics\fP\&.
.SS "virtual void GraphicsInterface::drawString (inty, intx, const char *s)\fC [pure virtual]\fP"

.PP
Implemented in \fBGraphics\fP\&.
.SS "virtual void GraphicsInterface::drawTile (inty, intx, unsigned inttile, \fBColor\fPfg, \fBColor\fPbg)\fC [pure virtual]\fP"

.PP
Implemented in \fBGraphics\fP\&.
.SS "virtual void GraphicsInterface::endScreenUpdate ()\fC [pure virtual]\fP"

.PP
Implemented in \fBGraphics\fP\&.
.SS "virtual void GraphicsInterface::initialise (intargc, char **argv)\fC [pure virtual]\fP"

.PP
Implemented in \fBGraphics\fP\&.
.SS "virtual void GraphicsInterface::setDisplayFunc (\fBDisplayFuncPtr\fPfunc)\fC [pure virtual]\fP"

.PP
Implemented in \fBGraphics\fP\&.
.SS "virtual void GraphicsInterface::setKeyboardFunc (\fBKeyboardFuncPtr\fPfunc)\fC [pure virtual]\fP"

.PP
Implemented in \fBGraphics\fP\&.
.SS "virtual void GraphicsInterface::setKeyboardUpFunc (\fBKeyboardFuncPtr\fPfunc)\fC [pure virtual]\fP"

.PP
Implemented in \fBGraphics\fP\&.
.SS "virtual void GraphicsInterface::setMouseFunc (\fBMouseFuncPtr\fPfunc)\fC [pure virtual]\fP"

.PP
Implemented in \fBGraphics\fP\&.
.SS "virtual void GraphicsInterface::spin ()\fC [pure virtual]\fP"

.PP
Implemented in \fBGraphics\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Fortress from the source code\&.
