.TH "Graphics" 3 "Fri Jul 24 2015" "Fortress" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Graphics \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <graphics\&.h>\fP
.PP
Inherits \fBGraphicsInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBinitialise\fP (int argc, char **argv)"
.br
.ti -1c
.RI "virtual void \fBspin\fP ()"
.br
.ti -1c
.RI "virtual void \fBdrawString\fP (int y, int x, const char *s)"
.br
.ti -1c
.RI "virtual void \fBdrawTile\fP (int y, int x, unsigned int tile, \fBColor\fP fg, \fBColor\fP bg)"
.br
.ti -1c
.RI "virtual void \fBdrawBorder\fP (int y, int x, int height, int width)"
.br
.ti -1c
.RI "virtual void \fBbeginScreenUpdate\fP ()"
.br
.ti -1c
.RI "virtual void \fBendScreenUpdate\fP ()"
.br
.ti -1c
.RI "virtual void \fBsetKeyboardFunc\fP (\fBKeyboardFuncPtr\fP func)"
.br
.ti -1c
.RI "virtual void \fBsetKeyboardUpFunc\fP (\fBKeyboardFuncPtr\fP func)"
.br
.ti -1c
.RI "virtual void \fBsetDisplayFunc\fP (\fBDisplayFuncPtr\fP func)"
.br
.ti -1c
.RI "virtual void \fBsetMouseFunc\fP (\fBMouseFuncPtr\fP func)"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBConfigManager\fP \fBm_config\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void Graphics::beginScreenUpdate ()\fC [virtual]\fP"

.PP
Implements \fBGraphicsInterface\fP\&.
.SS "void Graphics::drawBorder (inty, intx, intheight, intwidth)\fC [virtual]\fP"

.PP
Implements \fBGraphicsInterface\fP\&.
.SS "void Graphics::drawString (inty, intx, const char *s)\fC [virtual]\fP"

.PP
Implements \fBGraphicsInterface\fP\&.
.SS "void Graphics::drawTile (inty, intx, unsigned inttile, \fBColor\fPfg, \fBColor\fPbg)\fC [virtual]\fP"

.PP
Implements \fBGraphicsInterface\fP\&.
.SS "void Graphics::endScreenUpdate ()\fC [virtual]\fP"

.PP
Implements \fBGraphicsInterface\fP\&.
.SS "void Graphics::initialise (intargc, char **argv)\fC [virtual]\fP"

.PP
Implements \fBGraphicsInterface\fP\&.
.SS "void Graphics::setDisplayFunc (\fBDisplayFuncPtr\fPfunc)\fC [virtual]\fP"

.PP
Implements \fBGraphicsInterface\fP\&.
.SS "void Graphics::setKeyboardFunc (\fBKeyboardFuncPtr\fPfunc)\fC [virtual]\fP"

.PP
Implements \fBGraphicsInterface\fP\&.
.SS "void Graphics::setKeyboardUpFunc (\fBKeyboardFuncPtr\fPfunc)\fC [virtual]\fP"

.PP
Implements \fBGraphicsInterface\fP\&.
.SS "void Graphics::setMouseFunc (\fBMouseFuncPtr\fPfunc)\fC [virtual]\fP"

.PP
Implements \fBGraphicsInterface\fP\&.
.SS "void Graphics::spin ()\fC [virtual]\fP"

.PP
Implements \fBGraphicsInterface\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBConfigManager\fP Graphics::m_config\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fortress from the source code\&.
