.TH "graphics.cpp" 3 "Fri Jul 24 2015" "Fortress" \" -*- nroff -*-
.ad l
.nh
.SH NAME
graphics.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'graphics\&.h'\fP
.br
\fC#include <stdlib\&.h>\fP
.br
\fC#include <string\&.h>\fP
.br
\fC#include <GL/glut\&.h>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <SOIL\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "static void \fBempty\fP (void)"
.br
.ti -1c
.RI "static void \fBresize\fP (int w, int h)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "static void empty (void)\fC [static]\fP"

.SS "static void resize (intw, inth)\fC [static]\fP"

.SH "Author"
.PP 
Generated automatically by Doxygen for Fortress from the source code\&.
