.TH "main.cpp" 3 "Fri Jul 24 2015" "Fortress" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'gameengine\&.h'\fP
.br
\fC#include 'graphics\&.h'\fP
.br
\fC#include 'combat_system\&.h'\fP
.br
\fC#include 'sprite_system\&.h'\fP
.br
\fC#include 'movement_system\&.h'\fP
.br
\fC#include 'npc_system\&.h'\fP
.br
\fC#include <cstdlib>\fP
.br
\fC#include <iostream>\fP
.br
\fC#include <execinfo\&.h>\fP
.br
\fC#include <signal\&.h>\fP
.br

.SS "Functions"

.in +1c
.ti -1c
.RI "void \fBhandler\fP (int signal)"
.br
.ti -1c
.RI "int \fBmain\fP (int argc, char **argv)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "void handler (intsignal)"

.SS "int main (intargc, char **argv)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Fortress from the source code\&.
