.TH "splash_window.cpp" 3 "Fri Jul 24 2015" "Fortress" \" -*- nroff -*-
.ad l
.nh
.SH NAME
splash_window.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'splash_window\&.h'\fP
.br
\fC#include 'map_window\&.h'\fP
.br
\fC#include 'gameengine\&.h'\fP
.br
\fC#include 'graphics\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Fortress from the source code\&.
