.TH "SpriteComponent" 3 "Fri Jul 24 2015" "Fortress" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SpriteComponent \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sprite_component\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBColor\fP \fBfgColor\fP"
.br
.ti -1c
.RI "\fBColor\fP \fBbgColor\fP"
.br
.ti -1c
.RI "unsigned int \fBsprite\fP"
.br
.ti -1c
.RI "unsigned int \fBxPos\fP"
.br
.ti -1c
.RI "unsigned int \fByPos\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "\fBColor\fP SpriteComponent::bgColor"

.SS "\fBColor\fP SpriteComponent::fgColor"

.SS "unsigned int SpriteComponent::sprite"

.SS "unsigned int SpriteComponent::xPos"

.SS "unsigned int SpriteComponent::yPos"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fortress from the source code\&.
