.TH "sprite_system.cpp" 3 "Fri Jul 24 2015" "Fortress" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sprite_system.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'sprite_system\&.h'\fP
.br
\fC#include 'gameengine\&.h'\fP
.br
\fC#include 'event\&.h'\fP
.br
\fC#include 'sprite_component\&.h'\fP
.br
\fC#include <iostream>\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Fortress from the source code\&.
