.TH "TagValue" 3 "Fri Jul 24 2015" "Fortress" \" -*- nroff -*-
.ad l
.nh
.SH NAME
TagValue \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <config_manager\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "std::string \fBstr\fP"
.br
.ti -1c
.RI "long \fBnum\fP"
.br
.ti -1c
.RI "double \fBdec\fP"
.br
.in -1c
.SH "Member Data Documentation"
.PP 
.SS "double TagValue::dec"

.SS "long TagValue::num"

.SS "std::string TagValue::str"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fortress from the source code\&.
