.TH "WindowManager" 3 "Fri Jul 24 2015" "Fortress" \" -*- nroff -*-
.ad l
.nh
.SH NAME
WindowManager \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <window_manager\&.h>\fP
.PP
Inherits \fBWindowManagerInterface\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBinitialise\fP (\fBGameEngineInterface\fP *engine)"
.br
.ti -1c
.RI "void \fBaddWindow\fP (\fBWindowInterface\fP *win)"
.br
.ti -1c
.RI "void \fBpopWindow\fP ()"
.br
.ti -1c
.RI "void \fBreplaceWindow\fP (\fBWindowInterface\fP *win)"
.br
.ti -1c
.RI "\fBWindowInterface\fP * \fBgetActive\fP ()"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "\fBGameEngineInterface\fP * \fBm_engine\fP"
.br
.ti -1c
.RI "std::vector< \fBWindowInterface\fP * > \fBm_windows\fP"
.br
.in -1c
.SH "Member Function Documentation"
.PP 
.SS "void WindowManager::addWindow (\fBWindowInterface\fP *win)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBWindowManagerInterface\fP\&.
.SS "\fBWindowInterface\fP * WindowManager::getActive ()\fC [virtual]\fP"

.PP
Implements \fBWindowManagerInterface\fP\&.
.SS "void WindowManager::initialise (\fBGameEngineInterface\fP *engine)\fC [virtual]\fP"

.PP
Implements \fBWindowManagerInterface\fP\&.
.SS "void WindowManager::popWindow ()\fC [virtual]\fP"

.PP
Implements \fBWindowManagerInterface\fP\&.
.SS "void WindowManager::replaceWindow (\fBWindowInterface\fP *win)\fC [virtual]\fP"

.PP
Implements \fBWindowManagerInterface\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBGameEngineInterface\fP* WindowManager::m_engine\fC [private]\fP"

.SS "std::vector<\fBWindowInterface\fP*> WindowManager::m_windows\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fortress from the source code\&.
