.TH "Window" 3 "Fri Jul 24 2015" "Fortress" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Window \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <window\&.h>\fP
.PP
Inherits \fBWindowInterface\fP\&.
.PP
Inherited by \fBMapWindow\fP, and \fBSplashWindow\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBWindow\fP ()"
.br
.ti -1c
.RI "virtual \fB~Window\fP ()"
.br
.ti -1c
.RI "virtual void \fBinitialise\fP (\fBGameEngineInterface\fP *a_engine)"
.br
.ti -1c
.RI "virtual void \fBdestroy\fP (void)"
.br
.ti -1c
.RI "virtual \fBGameEngineInterface\fP * \fBgetEngine\fP ()"
.br
.ti -1c
.RI "virtual void \fBkeyDown\fP (unsigned char key)"
.br
.ti -1c
.RI "virtual void \fBkeyUp\fP (unsigned char key)"
.br
.ti -1c
.RI "virtual bool \fBgetKey\fP (unsigned char key)"
.br
.ti -1c
.RI "virtual void \fBmouseDown\fP (int x, int y, int button)"
.br
.ti -1c
.RI "virtual void \fBmouseUp\fP (int x, int y, int button)"
.br
.ti -1c
.RI "virtual bool \fBgetMouseButton\fP (int button)"
.br
.ti -1c
.RI "virtual void \fBbeforeRedraw\fP ()"
.br
.ti -1c
.RI "virtual void \fBredraw\fP ()"
.br
.ti -1c
.RI "virtual void \fBafterRedraw\fP ()"
.br
.ti -1c
.RI "virtual void \fBresize\fP (int width, int height)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static const int \fBMAX_BUTTONS\fP = 5"
.br
.in -1c
.SS "Private Attributes"

.in +1c
.ti -1c
.RI "bool \fBascii_keys\fP [256]"
.br
.ti -1c
.RI "bool \fBspecial_keys\fP [256]"
.br
.ti -1c
.RI "int \fBm_buttons\fP [\fBMAX_BUTTONS\fP]"
.br
.ti -1c
.RI "\fBGameEngineInterface\fP * \fBm_engine\fP"
.br
.in -1c
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Window::Window ()\fC [inline]\fP"

.SS "virtual Window::~Window ()\fC [inline]\fP, \fC [virtual]\fP"

.SH "Member Function Documentation"
.PP 
.SS "void Window::afterRedraw ()\fC [virtual]\fP"

.PP
Implements \fBWindowInterface\fP\&.
.SS "void Window::beforeRedraw ()\fC [virtual]\fP"

.PP
Implements \fBWindowInterface\fP\&.
.SS "void Window::destroy (void)\fC [virtual]\fP"

.PP
Implements \fBWindowInterface\fP\&.
.SS "virtual \fBGameEngineInterface\fP* Window::getEngine ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBWindowInterface\fP\&.
.SS "virtual bool Window::getKey (unsigned charkey)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBWindowInterface\fP\&.
.SS "bool Window::getMouseButton (intbutton)\fC [virtual]\fP"

.SS "void Window::initialise (\fBGameEngineInterface\fP *a_engine)\fC [virtual]\fP"

.PP
Implements \fBWindowInterface\fP\&.
.PP
Reimplemented in \fBMapWindow\fP\&.
.SS "virtual void Window::keyDown (unsigned charkey)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBWindowInterface\fP\&.
.PP
Reimplemented in \fBMapWindow\fP\&.
.SS "virtual void Window::keyUp (unsigned charkey)\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBWindowInterface\fP\&.
.SS "void Window::mouseDown (intx, inty, intbutton)\fC [virtual]\fP"

.PP
Implements \fBWindowInterface\fP\&.
.SS "void Window::mouseUp (intx, inty, intbutton)\fC [virtual]\fP"

.PP
Implements \fBWindowInterface\fP\&.
.SS "virtual void Window::redraw ()\fC [inline]\fP, \fC [virtual]\fP"

.PP
Implements \fBWindowInterface\fP\&.
.PP
Reimplemented in \fBMapWindow\fP, and \fBSplashWindow\fP\&.
.SS "void Window::resize (intwidth, intheight)\fC [virtual]\fP"

.PP
Implements \fBWindowInterface\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "bool Window::ascii_keys[256]\fC [private]\fP"

.SS "int Window::m_buttons[\fBMAX_BUTTONS\fP]\fC [private]\fP"

.SS "\fBGameEngineInterface\fP* Window::m_engine\fC [private]\fP"

.SS "const int Window::MAX_BUTTONS = 5\fC [static]\fP"

.SS "bool Window::special_keys[256]\fC [private]\fP"


.SH "Author"
.PP 
Generated automatically by Doxygen for Fortress from the source code\&.
