.TH "window_manager.cpp" 3 "Fri Jul 24 2015" "Fortress" \" -*- nroff -*-
.ad l
.nh
.SH NAME
window_manager.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'window_manager\&.h'\fP
.br
\fC#include 'splash_window\&.h'\fP
.br

.SH "Author"
.PP 
Generated automatically by Doxygen for Fortress from the source code\&.
