.TH "window_manager_interface.h" 3 "Fri Jul 24 2015" "Fortress" \" -*- nroff -*-
.ad l
.nh
.SH NAME
window_manager_interface.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'window_interface\&.h'\fP
.br
\fC#include 'game_engine_interface\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWindowManagerInterface\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Fortress from the source code\&.
