.TH "window.h" 3 "Fri Jul 24 2015" "Fortress" \" -*- nroff -*-
.ad l
.nh
.SH NAME
window.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <cstring>\fP
.br
\fC#include 'window_interface\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBWindow\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Fortress from the source code\&.
