---
Fullscreen: false
WindowWidth: 2182            # Only used if Fullscreen is set to false
WindowHeight: 1298           # Only used if Fullscreen is set to false
Tileset: Phoebus_16x16.png  # Used for tiles on the map
Tileset_Rows: 16
Tileset_Cols: 16
#Fontset: curses_16x16.png  # Used for text not on the map
Fontset: Md_curses_16x16.png  # Used for text not on the map
Fontset_Rows: 16
Fontset_Cols: 16
TileHeight: 24
TileWidth: 24
