#include "file_loader.h"
#include "../components/collider_component.h"
#include "../components/consumable_component.h"
#include "../components/description_component.h"
#include "../components/droppable_component.h"
#include "../components/equipment_component.h"
#include "../components/health_component.h"
#include "../components/npc_component.h"
#include "../components/player_component.h"
#include "../components/sprite_component.h"
#include "../components/connector_component.h"
#include "../components/wearable_component.h"
#include "../components/wieldable_component.h"
#include <fstream>
#include <glog/logging.h>
#include <iostream>
